# Generated by Django 3.0.8 on 2020-07-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': '运单', 'verbose_name_plural': '运单'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='logistics',
            options={'verbose_name': '物流公司', 'verbose_name_plural': '物流公司'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': '车辆', 'verbose_name_plural': '车辆'},
        ),
    ]
